services:
  - type: web
    name: python-flask-app
    env: python
    plan: free # optional; defaults to starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0 # Replace with your desired Python version
