disks:
  - name: data-disk
    sizeGB: 1

services:
  - type: web
    name: python-flask-app
    env: python
    plan: free # optional; defaults to starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --workers 1 app:app"
    disk:
      name: data-disk
      mountPath: /mnt/data
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0" # Ensured value is quoted, good practice
