services:
  - type: web
    name: python-flask-app
    env: python
    plan: free # optional; defaults to starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --workers 1 app:app"
    disk: # Using singular 'disk' directly in the service definition
      name: data-disk # Name for the disk resource
      mountPath: /mnt/data # Where to mount it
      sizeGB: 1 # Define size here as well
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
